### ISSUE TITLE
有没有第8章的笔记

### ISSUE THREAD

**Issue by Talbot3** [abcfy2/redis-in-action-reading-notes#1]
《Redis in Action》一书的第8章中提供了一个近乎完整的、类似于Twitter的社交网络的实现，包括关注者、列表、时间线、以及一个流服务器，这些内容对于理解如何使用Redis保存时间序列中的时间线及事件以及对查询的响应是一个很好的起点。

如果有相关内容的，能分享是最好的，谢了

**Comment by abcfy2** [comment]
并没有。redis我已经不用了，改用kafka了，所以这本读书笔记就搁置了
